name: test

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm run test

      - name: "notify vercel"
        uses: "vercel/repository-dispatch/actions/status@v1"
        with:
          name: "Vercel - fit-sync-front: test"
